### ISSUE TITLE
JSON parsing issue

### ISSUE THREAD

**Issue by dreamscached** [altea-minecraft/armor-statues-pack-ru#2]
[Copied from internal Trello]

```
[01:41:53] [Worker-Main-14/ERROR]: Couldn't parse loot table armor_statues:book/page_1
com.google.gson.JsonSyntaxException: Expected loot table to be a JsonObject, was an array (["",...}}])
at net.minecraft.util.ChatDeserializer.m(SourceFile:398) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.world.level.storage.loot.LootTable$b.a(LootTable.java:257) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.world.level.storage.loot.LootTable$b.deserialize(LootTable.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
at net.minecraft.world.level.storage.loot.LootTableRegistry.lambda$0(LootTableRegistry.java:47) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootTableRegistry.a(LootTableRegistry.java:45) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.world.level.storage.loot.LootTableRegistry.a(LootTableRegistry.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.ResourceDataAbstract.a(SourceFile:13) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:71) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:70) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:71) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:70) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:71) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:70) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:71) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.Reloadable.a(SourceFile:70) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at net.minecraft.server.packs.resources.Reloadable$1.a(SourceFile:53) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at net.minecraft.server.packs.resources.Reloadable$1.a(SourceFile:50) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by dreamscached** [comment]
Fixed in one of the previous commits since release 2.9.2-RU-1.0.1
